service: tap-note-dev

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  stage: dev

custom:
  defaultStage: dev

functions:
  main:
    handler: dist/main.handler
    name: ${self:provider.stage}-tap_note_sample
    description: '${self:provider.stage} tab noteのメイン関数(Nest.js)'
    runtime: nodejs16.x
    memorySize: 512
    timeout: 10 #(m)
    tracing: PassThrough # awsの他のサービスを実行するときに、トレース情報を自動的に送信する
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: '{proxy}'
          method: ANY
